import * as React from "react";
import type { AiTier, ArchetypeId, Budget, Catalog } from "../../../engine";

export interface SetupControlsProps { readonly catalog: Catalog; readonly budget: Budget; readonly aiTier: AiTier; readonly archetype: ArchetypeId | "any"; readonly seed: string; readonly onBudget:(value:Budget)=>void; readonly onTier:(value:AiTier)=>void; readonly onArchetype:(value:ArchetypeId|"any")=>void; readonly onSeed:(value:string)=>void; readonly onNewSeed:()=>void; }
export function SetupControls(p: SetupControlsProps): React.ReactElement {
 const tiers: readonly { value: AiTier; title:string; detail:string }[]=[{value:1,title:"TIER 1",detail:"GREEDY"},{value:2,title:"TIER 2",detail:"MODELLING"},{value:3,title:"TIER 3",detail:"DEEP SEARCH"}];
 return <div className="space-y-5">
  <fieldset><legend className="sl-label">POINT BUDGET</legend><div className="mt-2 grid grid-cols-8 border border-line">{([25,50,75,100,125,150,175,200] as readonly Budget[]).map(value=><button key={value} type="button" onClick={()=>p.onBudget(value)} className={`py-2 font-mono text-xs ${p.budget===value?"bg-sys text-void":"border-r border-line text-ink-2 hover:bg-panel-2"}`}>{value}</button>)}</div><p className="sl-help">EVERY SQUAD BUILDS AT {p.budget} · YOURS AND ALL FOUR AI</p></fieldset>
  <fieldset><legend className="sl-label">AI TIER</legend><div className="mt-2 grid grid-cols-3 border border-line">{tiers.map(t=><button key={t.value} type="button" onClick={()=>p.onTier(t.value)} className={`p-3 text-left ${p.aiTier===t.value?"bg-sys text-void":"border-r border-line text-ink-2 hover:bg-panel-2"}`}><span className="block text-xs font-semibold tracking-[.14em]">{t.title}</span><span className="font-mono text-[11px]">{t.detail}</span></button>)}</div><p className="sl-help">DECISION QUALITY ONLY · NO INFORMATION, POOL, STAT, OR BUDGET ADVANTAGE</p></fieldset>
  <fieldset><legend className="sl-label">MAP ARCHETYPE</legend><div className="mt-2 grid grid-cols-4 gap-px border border-line bg-line">{(["any",...p.catalog.mapArchetypes.map(a=>a.id)] as readonly (ArchetypeId|"any")[]).map(value=>{const a=value==="any"?null:p.catalog.indexes.archetypeById.get(value); return <button key={value} type="button" onClick={()=>p.onArchetype(value)} className={`min-h-16 bg-panel-2 p-2 text-left hover:bg-panel-3 ${p.archetype===value?"ring-1 ring-inset ring-sys text-sys":"text-ink-2"}`}><span className="block text-[11px] font-semibold uppercase tracking-[.1em]">{value==="any"?"ANY":a?.name}</span><span className="font-mono text-[10px]">{value==="any"?"SEEDED PICK":"FIXED"}</span></button>})}</div></fieldset>
  <label className="block"><span className="sl-label">MAP SEED</span><div className="mt-2 flex gap-2"><input aria-label="Map seed" value={p.seed} onChange={e=>p.onSeed(e.target.value)} className="min-w-0 flex-1 border border-line-2 bg-panel-3 px-3 py-2 font-mono text-sm text-ink" /><button type="button" onClick={p.onNewSeed} className="border border-line-2 px-3 text-xs tracking-[.12em] text-ink-2 hover:bg-panel-2">NEW SEED</button></div><span className="sl-help">A SEED IS REQUIRED BEFORE GENERATION. SAME SETTINGS + SEED = SAME SETUP.</span></label>
 </div>;
}
