import * as React from "react";
import { BUDGETS, encodeRoster, type AiTier, type ArchetypeId, type Budget } from "../../../engine";
import { createAiClient } from "../../bridge/ai-client";
import { browserMapGenWorker, createMapGenClient, createSetupGenerationService, createUserSeed, makeSetupDraft, resolveCatalog, rosterToEngineRoster, rosterViolations, selectorForArchetype, type PreparedSetup, type SetupGenerationService } from "../../store/build";
import { CollectionProvider, useCollection, useCollectionBinding } from "../../store/build";
import { useFlowStoreApi } from "../../store/core";
import { navigate } from "../../route-registry";
import { AiRosterReveal, MapPreview, RosterPicker, SetupControls, type HumanChoice } from "../../components/setup";

function Splash():React.ReactElement{return <main className="grid min-h-full place-items-center" role="status">LOADING MATCH SETUP…</main>}
function aiWorker(): Worker { return new Worker(new URL("../../../workers/ai.worker.ts", import.meta.url), {type:"module"}); }
function SetupContainer():React.ReactElement { const catalog=React.useMemo(()=>resolveCatalog(),[]); useCollectionBinding(); const collection=useCollection(s=>s.collection); const flow=useFlowStoreApi(); const [budget,setBudget]=React.useState<Budget>(BUDGETS[3]!); const [aiTier,setAiTier]=React.useState<AiTier>(2); const [archetype,setArchetype]=React.useState<ArchetypeId|"any">("any"); const [seed,setSeed]=React.useState(""); const [selected,setSelected]=React.useState<HumanChoice|null>(null); const [prepared,setPrepared]=React.useState<PreparedSetup|null>(null); const [busy,setBusy]=React.useState(false); const [error,setError]=React.useState<string|null>(null); const serviceRef=React.useRef<SetupGenerationService|null>(null); const currentRef=React.useRef<{cancel():void}|null>(null);
 React.useEffect(()=>{const service=createSetupGenerationService({map:createMapGenClient({factory:browserMapGenWorker}),ai:createAiClient({factory:aiWorker})}); serviceRef.current=service; return ()=>{currentRef.current?.cancel();service.dispose()};},[]);
 const invalidate=React.useCallback(()=>{currentRef.current?.cancel();currentRef.current=null;setPrepared(null);setError(null);setBusy(false)},[]);
 const selectHuman=React.useCallback((choice:HumanChoice)=>{setSelected(choice);invalidate()},[invalidate]);
 const newSeed=()=>{const result=createUserSeed(globalThis.crypto); if(result.kind==="ok"){setSeed(result.seed);invalidate()}else setError(result.message)};
 const generate=()=>{if(selected===null||seed.trim()===""||serviceRef.current===null)return; invalidate(); const draft=makeSetupDraft({budget,aiTier,selector:selectorForArchetype(archetype),seed}); const generation=serviceRef.current.prepare(draft,catalog); currentRef.current=generation; setBusy(true); void generation.result.then(result=>{if(currentRef.current!==generation)return;setBusy(false); if(result.kind==="ok")setPrepared(result.prepared);else setError(`${result.failure.stage}: ${result.failure.message}`)});};
 const canDeploy=selected!==null&&prepared!==null&&prepared.seed===seed&&prepared.budget===budget&&prepared.aiTier===aiTier&&JSON.stringify(prepared.selector)===JSON.stringify(selectorForArchetype(archetype));
 const deploy=()=>{if(!canDeploy||selected===null||prepared===null)return; const shares=prepared.aiRosters.map(r=>encodeRoster(r,budget,catalog)); const [a,b,c,d]=shares; if(a===undefined||b===undefined||c===undefined||d===undefined)return; flow.getState().setPendingLaunch({human:{source:selected.source,roster:selected.roster,shareString:encodeRoster(selected.roster,budget,catalog)},aiRosters:prepared.aiRosters,aiRosterShareStrings:[a,b,c,d],map:prepared.mapResult.map,seed,budget,aiTier,selector:prepared.selector,resolvedArchetypeId:prepared.mapResult.map.archetypeId});navigate("#/match")};
 const change=(apply:()=>void)=>{apply();invalidate()};
 return <main className="min-h-full bg-void text-ink" aria-labelledby="setup-title"><header className="flex h-12 items-center justify-between border-b border-line bg-panel px-4"><h1 id="setup-title" className="text-xs font-semibold uppercase tracking-[.14em]">SIGNAL LOSS / MATCH SETUP</h1><span className="font-mono text-[11px] text-sys">1 HUMAN + 4 AI = 5 SQUADS · NO TIMERS</span></header><div className="grid min-h-[calc(100vh-3rem)] grid-cols-[460px_1fr]"><aside className="border-r border-line bg-panel p-4"><SetupControls catalog={catalog} budget={budget} aiTier={aiTier} archetype={archetype} seed={seed} onBudget={v=>change(()=>setBudget(v))} onTier={v=>change(()=>setAiTier(v))} onArchetype={v=>change(()=>setArchetype(v))} onSeed={v=>change(()=>setSeed(v))} onNewSeed={newSeed}/><div className="my-5 border-t border-line"/><RosterPicker catalog={catalog} budget={budget} saved={collection?.rosters??[]} selected={selected} onSelect={selectHuman} toRoster={rosterToEngineRoster} prebuiltRoster={p=>({constructs:p.constructs.map(c=>({chassisCode:c.chassisCode,commanderCode:c.commanderCode,mounts:c.mounts}))})} violations={r=>rosterViolations(r,catalog)}/><button type="button" disabled={selected===null||seed.trim()===""||busy} onClick={generate} className="mt-5 w-full bg-sys px-4 py-3 text-sm font-semibold tracking-[.14em] text-void disabled:cursor-not-allowed disabled:bg-line-2">{busy?"GENERATING…":"GENERATE"}</button>{selected===null&&<p className="sl-help">SELECT A LEGAL ROSTER TO GENERATE.</p>}{seed.trim()===""&&<p className="sl-help">SET A CONCRETE SEED TO GENERATE.</p>}</aside><section className="space-y-5 p-5"><MapPreview result={prepared?.mapResult??null}/>{error!==null&&<div role="alert" className="border border-bad bg-panel p-3 font-mono text-xs text-bad">PREPARATION FAILED · {error}</div>}{prepared!==null&&<AiRosterReveal rosters={prepared.aiRosters} budget={budget} catalog={catalog}/>}<button type="button" disabled={!canDeploy} onClick={deploy} className="w-full border border-sys bg-sys/10 px-4 py-3 text-sm font-semibold tracking-[.14em] text-sys disabled:cursor-not-allowed disabled:border-line disabled:text-ink-4">DEPLOY</button></section></div></main> }
export function MatchSetup():React.ReactElement{return <CollectionProvider fallback={<Splash/>}><SetupContainer/></CollectionProvider>}
